[package]
name = "zellij-dashboard"
version = "0.1.0"
authors = ["Oliver Wooding <oliverwooding@icloud.com>"]
edition = "2021" # i'm an idiot; this refers to the cargo edition

[dependencies]
zellij-tile = "0.35.2"
